# Generated by Django 5.2.1 on 2025-05-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pokemon",
            table="pokemon",
        ),
        migrations.AlterModelTable(
            name="pokemonability",
            table="pokemon_ability",
        ),
        migrations.AlterModelTable(
            name="pokemontype",
            table="pokemon_type",
        ),
        migrations.AlterModelTable(
            name="pokemontyperelation",
            table="pokemon_type_relation",
        ),
    ]
