# Generated by Django 5.2.1 on 2025-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0002_alter_pokemon_table_alter_pokemonability_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="base_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
