# Generated by Django 5.2.1 on 2025-06-02 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0004_pokemonstats"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pokemonability",
            unique_together={("pokemon", "ability_name", "is_hidden")},
        ),
    ]
